// The remaining typed errors and wire details, against REAL servers:
//   - VersionNotSupportedError, from both the Python and the Java reference servers
//   - UnsupportedOperationError, generated by the Python server itself (streaming withheld;
//     subscribing to an already-finished task)
//   - the A2A-Extensions request header, as parsed by a real server
//   - content-type negotiation against the Java server (which rejects application/a2a+json)
// Python agents: 9700 (default), 9704 (INTEROP_NO_STREAMING=1). Java helloworld server: 9999.

import ballerina/a2a;
import ballerina/http;
import ballerina/io;

configurable string pythonUrl = "http://localhost:9700";
configurable string noStreamingUrl = "http://localhost:9704";
configurable string javaUrl = "http://localhost:9999";

int failures = 0;

function expect(string label, boolean ok, string detail = "") {
    io:println(ok ? "PASS: " : "FAIL: ", label, ok || detail == "" ? "" : " -- " + detail);
    if !ok {
        failures += 1;
    }
}

function nameOf(any|error v) returns string {
    return v is a2a:VersionNotSupportedError ? "VersionNotSupportedError"
        : v is a2a:UnsupportedOperationError ? "UnsupportedOperationError"
        : v is a2a:ContentTypeNotSupportedError ? "ContentTypeNotSupportedError"
        : v is a2a:Error ? "InternalError: " + v.message() : v is error ? "raw error" : "a success";
}

function msg(string id, string text = "hi") returns a2a:SendMessageRequest {
    return {message: {messageId: id, role: a2a:ROLE_USER, parts: [{text}]}};
}

function textOf(a2a:Task t) returns string {
    string out = "";
    foreach a2a:Artifact a in t?.artifacts ?: [] {
        foreach a2a:Part p in a.parts {
            out += p?.text ?: "";
        }
    }
    return out;
}

public function main() returns error? {
    io:println("== VersionNotSupportedError from both reference servers ==");
    foreach [string, string] [label, url] in [["Python a2a-sdk", pythonUrl], ["Java a2a-java", javaUrl]] {
        // The card is fetched normally; only the version header the client *sends* is wrong.
        a2a:AgentCard card = check a2a:resolveAgentCard(url, clientConfig = {httpVersion: http:HTTP_1_1});
        a2a:HttpClient c = check new (card, clientConfig = {httpVersion: http:HTTP_1_1},
                headers = {"A2A-Version": "2.0"});
        a2a:Task|a2a:Message|a2a:Error r = c->sendMessage(msg("ver-1"));
        expect(label + ": a real server's VERSION_NOT_SUPPORTED becomes VersionNotSupportedError",
                r is a2a:VersionNotSupportedError, nameOf(r));
    }

    io:println("== UnsupportedOperationError raised by a real server ==");
    a2a:AgentCard nsCard = check a2a:resolveAgentCard(noStreamingUrl);
    expect("the server withholds streaming (its card says so)", !nsCard.capabilities.streaming);
    nsCard.capabilities.streaming = true; // let the client believe it, so the *server* is what says no
    a2a:HttpClient liar = check new (nsCard);
    stream<a2a:StreamResponse, a2a:Error?>|a2a:Error st = liar->sendStreamingMessage(msg("uo-1"));
    expect("sendStreamingMessage against a non-streaming server", st is a2a:UnsupportedOperationError, nameOf(st));
    stream<a2a:StreamResponse, a2a:Error?>|a2a:Error sub = liar->subscribeToTask({id: "anything"});
    expect("subscribeToTask against a non-streaming server", sub is a2a:UnsupportedOperationError, nameOf(sub));

    a2a:HttpClient py = check new (pythonUrl);
    a2a:Task|a2a:Message|a2a:Error done = py->sendMessage(msg("uo-done"));
    if done is a2a:Task {
        stream<a2a:StreamResponse, a2a:Error?>|a2a:Error late = py->subscribeToTask({id: done.id});
        // Spec 3.1.6 says UnsupportedOperationError. The Python reference server (a2a-sdk 1.1.5) instead
        // answers 400 INVALID_PARAMS -- a deviation on *its* side (interop/RESULTS.md finding 13). The
        // client's job is to decode what it was given, faithfully: INVALID_PARAMS -> InternalError -32602.
        expect("the Python server's INVALID_PARAMS for a finished task is decoded as sent (client is faithful)",
                late is a2a:InternalError && !(late is a2a:UnsupportedOperationError) && late.detail().code == -32602,
                nameOf(late));
    }

    io:println("== the A2A-Extensions request header, as parsed by a real server ==");
    a2a:HttpClient withExt = check new (pythonUrl, requestedExtensions = ["urn:x:zeta", "urn:x:alpha"]);
    a2a:Task|a2a:Message|a2a:Error e1 = withExt->sendMessage(msg("interop-echo-extensions-1"));
    expect("two requested extensions arrive intact (the server sees both, in either order)",
            e1 is a2a:Task && textOf(e1) == "urn:x:alpha,urn:x:zeta", e1 is a2a:Task ? "server saw: " + textOf(e1) : nameOf(e1));
    a2a:Task|a2a:Message|a2a:Error e2 = py->sendMessage(msg("interop-echo-extensions-2"));
    expect("no extensions requested: none arrive", e2 is a2a:Task && textOf(e2) == "", e2 is a2a:Task ? "server saw: " + textOf(e2) : nameOf(e2));
    a2a:HttpClient javaExt = check new (javaUrl, clientConfig = {httpVersion: http:HTTP_1_1},
            requestedExtensions = ["urn:x:unknown"]);
    a2a:Task|a2a:Message|a2a:Error e3 = javaExt->sendMessage(msg("ext-java"));
    expect("an extension the Java server does not know is ignored, not an error", e3 is a2a:Task || e3 is a2a:Message, nameOf(e3));

    io:println("== content-type negotiation against the Java server (rejects application/a2a+json with 415) ==");
    a2a:HttpClient jc = check new (javaUrl, clientConfig = {httpVersion: http:HTTP_1_1});
    a2a:Task|a2a:Message|a2a:Error j1 = jc->sendMessage(msg("ct-1"));
    a2a:Task|a2a:Message|a2a:Error j2 = jc->sendMessage(msg("ct-2"));
    a2a:Task|a2a:Message|a2a:Error j3 = jc->sendMessage(msg("ct-3"));
    expect("the first call falls back to application/json and succeeds", j1 is a2a:Task || j1 is a2a:Message, nameOf(j1));
    expect("later calls keep working (the learnt choice is reused)", (j2 is a2a:Task || j2 is a2a:Message)
            && (j3 is a2a:Task || j3 is a2a:Message), nameOf(j2) + " / " + nameOf(j3));

    io:println(failures == 0 ? "\nOVERALL: PASS" : string `\nOVERALL: FAIL (${failures})`);
}
