// A third-language A2A agent for interop testing: @a2a-js/sdk 1.2.1 (A2A v1.0) over HTTP+JSON/REST only.
// If ANTHROPIC_API_KEY is set the reply is generated by Claude; otherwise a deterministic stub replies
// (the response says which one answered, so a run can never silently pass off the stub as the model).
//
//   text "slow ..."    -> WORKING for ~8s (cancellable), then COMPLETED
//   text "need input"  -> INPUT_REQUIRED; a follow-up on the same task completes it
//   text "msg: ..."    -> a direct Message reply (no task)
//   anything else      -> COMPLETED task with one text artifact
import express from 'express';
import Anthropic from '@anthropic-ai/sdk';
import { A2A_PROTOCOL_VERSION, AGENT_CARD_PATH, TaskState, Role } from '@a2a-js/sdk';
import { InMemoryTaskStore, DefaultRequestHandler, AgentEvent,
         InMemoryPushNotificationStore, DefaultPushNotificationSender } from '@a2a-js/sdk/server';
import { agentCardHandler, restHandler, UserBuilder } from '@a2a-js/sdk/server/express';

const PORT = Number(process.argv[2] || process.env.PORT || 9800);
const LLM = process.env.ANTHROPIC_API_KEY ? new Anthropic() : null;
const MODEL = process.env.CLAUDE_MODEL || 'claude-haiku-4-5-20251001';

const card = {
  name: 'Node A2A Interop Agent', description: '@a2a-js/sdk agent (HTTP+JSON only), ' + (LLM ? 'Claude-backed' : 'stub-backed'),
  supportedInterfaces: [{ url: `http://localhost:${PORT}` + (process.env.TRAILING_SLASH === "0" ? "" : "/"), protocolBinding: 'HTTP+JSON', tenant: '', protocolVersion: A2A_PROTOCOL_VERSION }],
  version: '1.0.0',
  capabilities: { streaming: true, pushNotifications: true, extensions: [], extendedAgentCard: false },
  securitySchemes: {}, securityRequirements: [],
  defaultInputModes: ['text'], defaultOutputModes: ['text'],
  skills: [{ id: 'chat', name: 'Chat', description: 'Answers questions', tags: ['chat'], examples: ['hi'], inputModes: ['text'], outputModes: ['text'], securityRequirements: [] }],
  signatures: [],
};

const textOf = (m) => (m?.parts ?? []).map((p) => p.content?.$case === 'text' ? p.content.value : '').join('');
const part = (t) => ({ content: { $case: 'text', value: t }, metadata: undefined, filename: '', mediaType: 'text/plain' });
const msg = (t, taskId, contextId) => ({ role: Role.ROLE_AGENT, messageId: crypto.randomUUID(), parts: [part(t)], taskId, contextId, extensions: [], metadata: {}, referenceTaskIds: [] });
const status = (taskId, contextId, state, message) => AgentEvent.statusUpdate({ taskId, contextId, status: { state, message, timestamp: new Date().toISOString() }, metadata: {} });

async function answer(prompt) {
  if (!LLM) return `[stub] echo: ${prompt}`;
  const r = await LLM.messages.create({ model: MODEL, max_tokens: 200, messages: [{ role: 'user', content: prompt }] });
  return `[claude] ${r.content.map((b) => b.text ?? '').join('')}`;
}

class Executor {
  cancelled = new Set();
  cancelTask = async (taskId) => { this.cancelled.add(taskId); };
  async execute(ctx, bus) {
    const { taskId, contextId, userMessage: um, task } = ctx;
    const text = textOf(um);
    if (text.startsWith('msg:')) { bus.publish(AgentEvent.message(msg(await answer(text.slice(4)), undefined, contextId))); return; }
    bus.publish(AgentEvent.task(task ?? { id: taskId, contextId, status: { state: TaskState.TASK_STATE_SUBMITTED, timestamp: new Date().toISOString(), message: undefined }, artifacts: [], history: [um], metadata: um.metadata }));
    if (text.includes('need input') && !task) { bus.publish(status(taskId, contextId, TaskState.TASK_STATE_INPUT_REQUIRED, msg('Which city?', taskId, contextId))); return; }
    bus.publish(status(taskId, contextId, TaskState.TASK_STATE_WORKING, msg('Working', taskId, contextId)));
    if (text.startsWith('slow')) {
      for (let i = 0; i < 16; i++) {
        await new Promise((r) => setTimeout(r, 500));
        if (this.cancelled.has(taskId)) { this.cancelled.delete(taskId); bus.publish(status(taskId, contextId, TaskState.TASK_STATE_CANCELED)); return; }
      }
    }
    const reply = await answer(text);
    bus.publish(AgentEvent.artifactUpdate({ taskId, contextId, artifact: { artifactId: crypto.randomUUID(), name: 'Result', description: '', parts: [part(reply)], metadata: undefined, extensions: [] }, lastChunk: true, append: false, metadata: undefined }));
    bus.publish(status(taskId, contextId, TaskState.TASK_STATE_COMPLETED));
  }
}

const store = new InMemoryTaskStore();
const pushStore = new InMemoryPushNotificationStore();
const handler = new DefaultRequestHandler(card, store, new Executor(), undefined, pushStore, new DefaultPushNotificationSender(pushStore));
const app = express();
app.use(`/${AGENT_CARD_PATH}`, agentCardHandler({ agentCardProvider: handler }));
app.use('/', restHandler({ requestHandler: handler, userBuilder: UserBuilder.noAuthentication }));
app.listen(PORT, () => console.log(`node agent on http://localhost:${PORT} (${LLM ? 'Claude ' + MODEL : 'stub'})`));
